name: Deploy

on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    uses: GitLaw-co/k8s/.github/workflows/deploy-triggerer.yml@main
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
    with:
      apps: documenso
